matrix:
  include:
    -
      language: node_js
      node_js:
        - node
      cache:
        directories:
          - $HOME/.npm
      script:
        - npm run coverage
    -
      language: php
      php: 7.1
      cache:
        directories:
          - $HOME/.composer/cache/files
      install:
        - "cd api"
        - "composer install"
      script:
        - "./vendor/bin/phpunit --configuration='phpunit.xml' --testdox --coverage-clover=coverage.xml"
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
