matrix:
  include:
    -
      language: node_js
      node_js:
        - node
    -
      install: "composer install"
      language: php
      script:
        - "./vendor/bin/phpunit tests --testdox"
notifications:
  email: false
