matrix:
  include:
    -
      language: node_js
      node_js:
        - node
      cache:
        directories:
          - $HOME/.npm
      script:
        - npm run coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    -
      install:
        - "cd api"
        - "composer install"
      language: php
      php: 7.1
      script:
        - "./vendor/bin/phpunit tests --testdox"
notifications:
  email: false
