matrix:
  include:
    -
      language: node_js
      node_js:
        - node
    -
      install:
        - "cd api"
        - "composer install"
      language: php
      php:
        - "7.1"
      script:
        - "./vendor/bin/phpunit tests --testdox"
notifications:
  email: false
